FROM hub.c.163.com/nce2/nodejs:0.12.2  # Create app directory
RUN npm install --registry=https://registry.npm.taobao.org

#RUN mkdir -p /home/Service
#WORKDIR /home/Service
#COPY . /home/Service
#RUN npm install
#EXPOSE 3002
#CMD npm start
 ## 如果想运行多条指令可以这样：
## CMD git pull && npm install && npm start