version: '2'
services:
#  nginx:
#    build:
#      context: ./
#      dockerfile: services/nginx/docker/Dockerfile
#    #image: daocloud.io/nginx:1.13-alpine
#    restart: always
#    container_name: nginx
#    volumes:
#      - "./app:/var/www"
#      - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
#      - "/etc/nginx/conf.d:/etc/nginx/conf.d"
#      - "/usr/local/nginx/logs:/var/log/nginx"
#
#    ports:
#      - "8081:80"
##    depends_on:
##      - php
##      - mysql
##      - redis
##      - memcached
#    networks:
#      - code-network


  # The application
  web:
    image: nginx:latest
    build:
      context: './'
      dockerfile: 'services/nginx/docker/Dockerfile'
    ports:
      - "8081:80"
    restart: always
    volumes:
      - ./app:/www/web
      - "/services/nginx/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - ./services/web/nginx/conf.d:/etc/nginx
      - ./services/web/nginx/logs:/www/web_logs
    depends_on:
      - php
    networks:
      - code-network
  php:
    build:
      context: './'
      dockerfile: services/php/docker/Dockerfile
    restart: always
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    depends_on:
      - mysql
    networks:
      - code-network
  mysql:
    image: daocloud.io/mysql:5.7.4
    volumes:
      - ./services/mysql/data:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=astystore"
      #- "MYSQL_USER=homestead"
      #- "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=123456"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - code-network

#  nodeapp1:
#    build:
#      context: './services/nodejs/docker/Dockerfile'
##    working_dir: /var/www
##    volumes:
##        - app: /var/www
#    ports:
#      - "3002:3002"
#    networks:
#      - code-network
#  redis:
#    image: redis:4.0
#    restart: always
#    environment:
#      REDIS_PASS_FILE: /run/secrets/redis-password
#    command: [
#      "bash", "-c",
#      '
#         docker-entrypoint.sh
#         --requirepass "$$(cat $$REDIS_PASS_FILE)"
#        '
#    ]
#    volumes:
#      - ./services/redis/etc/redis.conf:/usr/local/etc/redis/redis.conf
#      - ./services/redis/data:/data
#      - ./services/redis/etc/redis-password:/run/secrets/redis-password
#    networks:
#      - code-network
#  elasticsearch:
#    build: ./services/elasticsearch/docker/Dockerfile
#    volumes:
#      - /services/elasticsearch/data:/usr/share/elasticsearch/data
#      - /services/elasticsearch/plugins:/usr/share/elasticsearch/plugins
#    environment:
#      - cluster.name=laradock-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    mem_limit: 512m
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    depends_on:
#      - php
#    networks:
#      - code-network
networks:
  code-network:
    driver: bridge